In [2]:
import pandas as pd
import sklearn as sk

In [3]:
df = pd.read_csv("feature_updated.csv", low_memory=False)

In [3]:
### STANDARD SETUP

features = df.columns
to_exclude = ['code', 'status', 'year', 'month', 'dataset', 'split', 'author', 'category', 'MV']
features = [x for x in features if x not in to_exclude]
# from 0 to 2152: metadata features; from 2152 to 6152 (end): code features
# if you want to use the "combined classifier", choose all features

label = 'status'
threshold = 0.912 # this was derived by Ben

In [4]:
def test_clf(clf, test_set, features=features, label=label, threshold=threshold):
    '''Handy function to test a classifier, compute the probabilities and print results'''
    pred = clf.predict(test_set[features])
    probabilities = clf.predict_proba(test_set[features])


    y_pred = []
    for prob in probabilities:
        if prob[0] >= threshold:
            y_pred.append("benign")
        else:
            y_pred.append("malware")


    acc = sk.metrics.accuracy_score(test_set[label], y_pred)
    prec = sk.metrics.precision_score(test_set[label], y_pred, pos_label='malware')
    rec = sk.metrics.recall_score(test_set[label], y_pred, pos_label='malware')
    fpr = 1-sk.metrics.recall_score(test_set[label], y_pred, pos_label='benign')



    print("Accuracy: {:.2f}%,\tPrecision: {:.2f}%\tRecall: {:.2f}%\tFPR: {:.5f}".format(acc*100, prec*100, rec*100, fpr))

    display(pd.crosstab(test_set[label], y_pred, rownames=['True'], colnames=['Pred']))


    return probabilities, acc, prec, rec, fpr

In [5]:
### First, let's re-create the datasets as they should be

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from datetime import datetime


df_2022 = df[df['year']<=2022]
df_2022_benign = df_2022[df_2022['status']=='benign']
df_2022_malicious = df_2022[df_2022['status']=='malware']

In [6]:
# EXPERIMENT 1: changing the threshold to reduce false positives (we redo this 5 times)

In [ ]:
fpr_list = []
rec_list = []

threshold_to_test = 0.65

for i in range(5):
    print("\n\nROUND {}\n\n".format(i))
    train_ben, test_ben = train_test_split(df_2022_benign, test_size=0.2, random_state=i)
    train_mal, test_mal = train_test_split(df_2022_malicious, test_size=0.2, random_state=i)
    train = pd.concat([train_ben, train_mal])
    test=pd.concat([test_ben,test_mal])
    ## Define and train the classifier
    rf = RandomForestClassifier(n_estimators=300, max_features="sqrt", criterion="gini",
                                       n_jobs=-2, class_weight="balanced", random_state=i)
    start = datetime.now()
    rf.fit(train[features], train[label])
    print(f"Training time: f{datetime.now()- start}")
    end = datetime.now()


    ## Test the classifier
    prob, acc_def, prec_def, rec_def, fpr_def = test_clf(rf, test)
    print(f"Test time: f{datetime.now()- end}")
    prob, acc_new, prec_new, rec_new, fpr_new = test_clf(rf, test, threshold=threshold_to_test)
    fpr_list.append((fpr_def, fpr_new))
    rec_list.append((rec_def, rec_new))

ROUND 0


Training time: f0:00:21.306311
Accuracy: 98.74%,	Precision: 91.40%	Recall: 96.49%	FPR: 0.01005

Pred     benign  malware
True
benign    12213      124
malware      48     1318

Test time: f0:00:01.105646
Accuracy: 99.07%,	Precision: 99.68%	Recall: 91.00%	FPR: 0.00032

Pred     benign  malware
True
benign    12333        4
malware     123     1243

ROUND 1


Training time: f0:00:20.689324
Accuracy: 98.58%,	Precision: 90.63%	Recall: 95.61%	FPR: 0.01094

Pred     benign  malware
True
benign    12202      135
malware      60     1306

Test time: f0:00:01.137729
Accuracy: 99.01%,	Precision: 99.68%	Recall: 90.34%	FPR: 0.00032

Pred     benign  malware
True
benign    12333        4
malware     132     1234

ROUND 2


Training time: f0:00:20.692398
Accuracy: 98.71%,	Precision: 91.54%	Recall: 95.90%	FPR: 0.00981

Pred     benign  malware
True
benign    12216      121
malware      56     1310

Test time: f0:00:01.150962
Accuracy: 99.04%,	Precision: 99.28%	Recall: 91.00%	FPR: 0.00073

Pred     benign  malware
True
benign    12328        9
malware     123     1243

ROUND 3


Training time: f0:00:18.469545
Accuracy: 98.58%,	Precision: 91.04%	Recall: 95.17%	FPR: 0.01038

Pred     benign  malware
True
benign    12209      128
malware      66     1300

Test time: f0:00:01.136776
Accuracy: 98.94%,	Precision: 99.51%	Recall: 89.82%	FPR: 0.00049

Pred     benign  malware
True
benign    12331        6
malware     139     1227

ROUND 4

In [11]:
rec_list.append((rec_def, rec_new))
avg_fpr_new = (fpr_list[0][1] + fpr_list[1][1] + fpr_list[2][1] + fpr_list[3][1] + fpr_list[4][1]) / 5
avg_fpr_def = (fpr_list[0][0] + fpr_list[1][0] + fpr_list[2][0] + fpr_list[3][0] + fpr_list[4][0]) / 5

avg_rec_new = (rec_list[0][1] + rec_list[1][1] + rec_list[2][1] + rec_list[3][1] + rec_list[4][1]) / 5
avg_rec_def = (rec_list[0][0] + rec_list[1][0] + rec_list[2][0] + rec_list[3][0] + rec_list[4][0]) / 5

print("Original FPR: {:.6f}\tNew FPR: {:.6f}".format(avg_fpr_def, avg_fpr_new))
print("Original TPR: {:.6f}\tNew TPR: {:.6f}".format(avg_rec_def, avg_rec_new))

Original FPR: 0.010748	New FPR: 0.000470
Original TPR: 0.957101	New TPR: 0.905417

In [ ]:
# EXPERIMENT 2: subsampling benign extensions to balance the dataset (and hoping for a better baseline performance)

In [12]:
for i in range(1): # repeat it as many times as you want
    print("\n\nROUND {}\n\n".format(i))
    for j in [0.1, 0.2, 0.4, 0.8]: # specify the size of each draw


        sub_train_ben = train_ben.sample(n=(int(len(train_ben)*j)), random_state=i)
        sub_train = pd.concat([sub_train_ben, train_mal])

        print("\tSubset: {} --> Benign samples: {}\t Malicious samples: {}".format(j,len(sub_train_ben), len(train_mal)))

        ## Define and train the classifier
        rf_sub = RandomForestClassifier(n_estimators=300, max_features="sqrt", criterion="gini",
                                           n_jobs=-2, class_weight="balanced", random_state=1)
        start = datetime.now()
        rf_sub.fit(sub_train[features], sub_train[label])
        print(f"Training time: f{datetime.now()- start}")


        ## Test the classifier

        prob_, acc, prec, rec, fpr = test_clf(rf_sub, test)

ROUND 0


	Subset: 0.1 --> Benign samples: 4934	 Malicious samples: 5464
Training time: f0:00:02.579055
Accuracy: 59.74%,	Precision: 19.81%	Recall: 99.71%	FPR: 0.44687

Pred     benign  malware
True
benign     6824     5513
malware       4     1362

	Subset: 0.2 --> Benign samples: 9869	 Malicious samples: 5464
Training time: f0:00:04.094036
Accuracy: 80.46%,	Precision: 33.67%	Recall: 99.05%	FPR: 0.21602

Pred     benign  malware
True
benign     9672     2665
malware      13     1353

	Subset: 0.4 --> Benign samples: 19738	 Malicious samples: 5464
Training time: f0:00:08.251405
Accuracy: 93.23%,	Precision: 59.80%	Recall: 97.80%	FPR: 0.07279

Pred     benign  malware
True
benign    11439      898
malware      30     1336

	Subset: 0.8 --> Benign samples: 39477	 Malicious samples: 5464
Training time: f0:00:17.095210
Accuracy: 97.94%,	Precision: 85.15%	Recall: 96.12%	FPR: 0.01856

Pred     benign  malware
True
benign    12108      229
malware      53     1313